accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('', views.feed_view, name='feed_index'),
    path('curtir/', views.curtir, name='curtir'),
    path('interesse/', views.interesse, name='curtir'),
    path('publication/', views.create_publication, name='publication')
]

campusbroadcast/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('landingpage.urls', namespace='landingpage')),
    path('accounts/', include('accounts.urls', namespace='accounts') ),
] 


if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )

landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('donate/', views.donate_view, name='doacao'),
]

landingpage/models.py
from django.db import models
from django.utils import timezone

class Itens(models.Model):
    nome_alimento = models.CharField(max_length=30, null=True, blank=True)


    def __str__(self):
        return self.nome_alimento

class Donate(models.Model):
    nome = models.CharField(max_length=500, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    telefone = models.CharField(max_length=25, null=True, blank=True)

    LOCAL_CHOICES = (
        ('prefeitura', 'prefeitura'),
        ('igreja', 'igreja'),
        ('praca', 'praça')
    )

    local = models.CharField(max_length=50, choices=LOCAL_CHOICES, null=True, blank=True)

    itens = models.ManyToManyField(Itens, related_name='itens_doado')

    data = models.DateTimeField(default=timezone.now, blank=False)

    def __str__(self):
        return self.nome

landingpage/forms.py
from django import forms
from .models import Donate

class DonateForm(forms.ModelForm):
    class Meta:
        model = Donate
        fields = ['nome', 'email', 'telefone', 'local', 'itens']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Adiciona classes CSS ou outros atributos, se necessário
        self.fields['itens'].widget.attrs.update({'class': 'seletor-itens-multiplo', 'multiple': 'multiple'})

landingpage/views.py
from django.shortcuts import render, redirect
from accounts.models import Palestrante
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import DonateForm
from .models import Donate
from django.core.serializers import serialize


def landing_page(request):
    if request.user.is_authenticated:
        return redirect('accounts:feed_index')

    objects_palestrantes = Palestrante.objects.all()
    return render(request, 'landingpage/index.html', {'palestrantes': objects_palestrantes})


@csrf_exempt
def donate_view(request):
    if request.method == "POST":
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        telefone = request.POST.get('telefone')
        local = request.POST.get('local')
        itens = request.POST.get('itens')


        form = DonateForm(request.POST)
        if form.is_valid():
            donate_instance = form.save()
            return JsonResponse({'status': 'success', 'id': donate_instance.id})
        else:
            return JsonResponse({'status': 'error', 'errors': form.errors}, status=400)

    donate_objects = Donate.objects.all()

    data_list = []
    for donate_object in donate_objects:
        # Acesse os campos do objeto 'Donate' e adicione-os à lista de dados
        data_list.append({
            'nome': donate_object.nome,
            'email': donate_object.email,
            'telefone': donate_object.telefone,
            'local': donate_object.local,
            'itens': [item.nome_alimento for item in donate_object.itens.all()],
            'data': donate_object.data.strftime('%Y-%m-%d'),  # Formate a data conforme necessário
        })

    # Crie um JSON manualmente
    data_json = {'data': data_list}

    return JsonResponse(data_json, safe=False)

landingpage/templates/landingpage/index.html
{% extends 'base.html' %}
{% load static %}

{% block 'titulo' %}Landing Page{% endblock %}
{% block 'styles' %}<link rel="stylesheet" href="{% static 'landingpage/styles.css' %}">{% endblock %}

{% block 'conteudo' %}

    <header>
        <div class="area-header">
            <h1 class="logoName">Campus<span>Broadcast</span></h1>
        </div>
    </header>

    <section class="sectionBanner">
        <div class="areaBanner">
            <div class="logoBtnInscreva">
                <img src="{%static 'landingpage/imagens/logoCampus.svg'%}" alt="img">
                <a href="{%url 'accounts:register'%}">Inscreva-se</a>
            </div>

            <form action="{%url 'accounts:login'%}" method="POST" class="login">
                {%csrf_token%}
                <h2>Entrar</h2>
    
                <input type="email" placeholder="Email" name="email" aria-label="Email">
            
                <input type="password" placeholder="Senha" name="password" aria-label="Senha">
                <a href="#">Esqueci a senha</a>
                <button type="submit">Entrar</button>
            </form>
        </div>
    </section>

    <section class="sectionFunctions">
        <ul class="container-functions">
            <li id="function1">
                <img src="{%static 'landingpage/imagens/alerta_relogio.png'%}" alt="img">
                <h2>Alerte sobre eventos</h2>
                <p>Receba alertas sobre conferências, palestras e atividades no nosso campus</p>
            </li>

            <li id="function2">
                <img src="{%static 'landingpage/imagens/alertasforusuario.png'%}" alt="img">
                <h2>Receba Alertas</h2>
                <p>Mantenha-se atualizado com notícias e informações relevantes para a nossa comunidade acadêmica.</p>
            </li>

            <li id="function3">
                <img src="{%static 'landingpage/imagens/usercomunacation.png'%}" alt="img">
                <h2>Converse e Interaja</h2>
                <p>Use nossos chats para se comunicar com colegas, professores e grupos de interesse. Participe da conversa!</p>
            </li>
        </ul>
    </section>

    <section class="sectionPalestrantes">
        <div class="area-palestrantes">
            <h2>Nossos palestrantes</h2>
            <ul class="palestranteContainer">
                {%for palestrante in palestrantes%}
                    <li>
                        <div class="area-img-palestrante">
                            {%if palestrante.photo%}
                                <img src="{{palestrante.photo.url}}" alt="img">
                            {%endif%}
                        </div>
                        <h3>{{palestrante.first_name}} {{palestrante.last_name}}</h3>
                        <p>{{palestrante.training}}</p>
                        {%if palestrante.is_visitant%}
                            <span>Visitante</span>
                        {%endif%}
                    </li>
                {%endfor%}
            </ul>
        </div>
    </section>

    <section class="sectionObjective">
        <div class="area-objective">
            <article>
                <h2>Nosso <span>Objetivo</span></h2>
                <ul class="container-list-bjective">
                    <li>
                        <span>Aumentar o Engajamento da Comunidade:</span> 
                        Fomentar a participação ativa dos alunos, professores e funcionários, 
                        promovendo o envolvimento em eventos, discussões e atividades no campus.
                    </li>

                    <li>
                        <span>Melhorar a Comunicação:</span> 
                        Aperfeiçoar a comunicação interna no campus, assegurando que informações relevantes, 
                        anúncios e atualizações estejam disponíveis para todos os membros da comunidade acadêmica.
                    </li>

                    <li>
                        <span>Promover Eventos e Atividades:</span> 
                        Facilitar a divulgação de eventos e atividades no campus e aumentar a participação 
                        nesses eventos.
                    </li>

                    <li>
                        <span>Facilitar a Segmentação de Mensagens:</span> 
                        Capacitar a administração para direcionar mensagens e anúncios específicos para 
                        grupos ou departamentos específicos quando necessário.
                    </li>

                    <li>
                        <span>Fomentar a Interação e Networking:</span> 
                        Promover interações significativas entre alunos, professores e funcionários, além de 
                        facilitar oportunidades de networking.
                    </li>

                    <li>
                        <span>Melhorar a Participação em Eventos:</span> 
                        Aumentar o número de inscrições e participações em eventos, como conferências, 
                        palestras e workshops.
                    </li>

                    <li>
                        <span>Promover uma Cultura de Campus Ativa:</span> 
                        Fomentar uma cultura de envolvimento ativo no campus, onde os membros da comunidade 
                        acadêmica estejam cientes de eventos, compartilhem ideias e participem ativamente das atividades.
                    </li>
                </ul>
            </article>
            <div class="img-area">
                <img src="{%static 'landingpage/imagens/objective.svg'%}" alt="objetivo">
            </div>
        </div>
    </section>

    <footer>
        <div class="area-footer">
            <p>&copy; Marcelo</p>
            <nav class="navBar-footer">
                <a href="https://www.instagram.com/marcelo.ftp/" target="_blank"><img src="{%static 'landingpage/imagens/instagram_icon.svg'%}" alt="instagram"></a>
                <a href="https://www.linkedin.com/in/marcelo-araujo-2026841b4/" target="_blank"><img src="{%static 'landingpage/imagens/linkedin_icon.svg'%}" alt="linkedin"></a>
                <a href="https://marcelo.araujo.999s@gmail.com" target="_blank"><img src="{%static 'landingpage/imagens/mail_icon.svg'%}" alt="email"></a>
                <a href="https://github.com/marcelo-py" target="_blank"><img src="{%static 'landingpage/imagens/github_icon.svg'%}" alt="github"></a>
            </nav>
        </div>
    </footer>
{% endblock %}